#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <cmath>
#include <cassert>

// Include your actual robot code header
#include "../controller.hpp"

double tolerance = 0.05; // Allowable error for floating point comparisons

int main() {
    std::cout << "Starting Controller Unit Test... Tolerance: " << tolerance << std::endl;

    // Open the CSV file generated by MATLAB
    std::ifstream file("test_data.csv");
    if (!file.is_open()) {
        std::cerr << "Error: Could not open test_data.csv" << std::endl;
        return 1;
    }

    std::string line;
    bool is_header = true;
    double dt = 0.006; // Must match MATLAB
    
    AngleController robot_controller;
    
    int row_count = 0;
    int passed_tests = 0;

    // Read CSV line by line
    while (std::getline(file, line)) {
        if (is_header) {
            is_header = false; // Skip the first row (column names)
            continue;
        }

        std::stringstream ss(line);
        std::string cell;
        std::vector<double> row_data;

        // Parse comma-separated values
        while (std::getline(ss, cell, ',')) {
            row_data.push_back(std::stod(cell));
        }

        // Map CSV columns (Updated for the new column layout)
        double theta_meas             = row_data[1];
        double expected_theta_hat     = row_data[2];
        double expected_theta_dot_hat = row_data[3]; // NEW
        double expected_u             = row_data[4]; // Shifted from [3] to [4]

       // Run your actual C++ code
        double calculated_u = robot_controller.Controller(theta_meas, dt);
        
        // You would need a getter in your class to read this variable for testing:
        // double calculated_theta_hat = robot_controller.get_theta_hat(); 

        // --- ASSERTIONS (The Proof) ---
        // Allow a small tolerance for floating point rounding differences

        bool u_matches = std::abs(calculated_u - expected_u) < tolerance;
        
        if (!u_matches) {
            std::cout << "----------------------------------------" << std::endl;
            std::cerr << "TEST FAILED at row " << row_count + 1 << std::endl;
            std::cerr << "Time: " << row_data[0] << " s" << std::endl;
            std::cerr << "Measured: " << theta_meas << std::endl;
            std::cerr << "Expected u: " << expected_u << " | Calculated u: " << calculated_u << std::endl;
            std::cout << "----------------------------------------" << std::endl;
            return 1; // Halt the program entirely
        }

        passed_tests++;
        row_count++;
    }

    std::cout << "ALL TESTS PASSED! Successfully validated " << passed_tests << " control loop cycles." << std::endl;
    return 0;
}